services:
  app:
    build: .
    ports:
      - '${PORT:-5051}:5050'
    env_file:
      - .env
    environment: # optionally define in -e argument when running docker command
      API_KEY: ${API_KEY:-your_api_key_here}
      PORT: ${PORT:-5050}
      DEFAULT_VOICE: ${DEFAULT_VOICE:-en-US-AndrewNeural}
      DEFAULT_RESPONSE_FORMAT: ${DEFAULT_RESPONSE_FORMAT:-mp3}
      DEFAULT_SPEED: ${DEFAULT_SPEED:-4}
      REQUIRE_API_KEY: ${REQUIRE_API_KEY:-True}
      REMOVE_FILTER: ${REMOVE_FILTER:-False}
      EXPAND_API: ${EXPAND_API:-True}

    volumes:
      # 如果想要实现在宿主机修改config.json然后通过 #reconf 热更新配置
      # 请执行 chmod 666 config.json，增加容器对宿主机的config.json文件修改权限
      # 注意环境变量配置优先级高于config.json配置
      - ./voice_mappings.json:/app/voice_mappings.json
